// <auto-generated />
using EntityFrameworkSQLite.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFrameworkSQLite.Migrations
{
    [DbContext(typeof(OrderDbContext))]
    [Migration("20190418133005_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("EntityFrameworkSQLite.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Name = "MSDN Order"
                        },
                        new
                        {
                            OrderId = 2,
                            Name = "Docker Order"
                        },
                        new
                        {
                            OrderId = 3,
                            Name = "EFCore Order"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
